name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install-command: npm install --legacy-peer-deps
          browser: chrome
          headed: true
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000
          record: false
          component: false
